# Generated by Django 5.1.1 on 2025-02-05 07:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('user', 'portfolio_name')},
        ),
    ]
